"""initial schema

Revision ID: 5c9b22bdbf25
Revises: 
Create Date: 2026-08-26 11:06:06.640775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9b22bdbf25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_metadata',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('energy_hourly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp_local', sa.DateTime(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('ean_number', sa.String(length=64), nullable=False),
    sa.Column('withdrawn_kwh_milli', sa.Integer(), nullable=False),
    sa.Column('injected_kwh_milli', sa.Integer(), nullable=False),
    sa.Column('balance_withdrawn_minus_injected_kwh_milli', sa.Integer(), nullable=False),
    sa.Column('spot_price_eur_kwh_micro', sa.Integer(), nullable=True),
    sa.Column('injected_value_eur_micro', sa.Integer(), nullable=True),
    sa.Column('energy_point_count', sa.Integer(), nullable=False),
    sa.Column('price_point_count', sa.Integer(), nullable=False),
    sa.Column('energy_complete', sa.Boolean(), nullable=False),
    sa.Column('price_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name', 'ean_number', 'timestamp_utc', name='uq_energy_hourly')
    )
    with op.batch_alter_table('energy_hourly', schema=None) as batch_op:
        batch_op.create_index('ix_energy_hourly_site_ean', ['site_name', 'ean_number'], unique=False)
        batch_op.create_index('ix_energy_hourly_timestamp', ['timestamp_utc'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_totals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('ean_number', sa.String(length=64), nullable=False),
    sa.Column('withdrawn_kwh_milli', sa.Integer(), nullable=False),
    sa.Column('injected_kwh_milli', sa.Integer(), nullable=False),
    sa.Column('net_injected_minus_withdrawn_kwh_milli', sa.Integer(), nullable=False),
    sa.Column('injected_value_eur_micro', sa.Integer(), nullable=False),
    sa.Column('average_spot_price_eur_kwh_micro', sa.Integer(), nullable=True),
    sa.Column('negative_price_hours', sa.Integer(), nullable=False),
    sa.Column('hours_with_missing_energy', sa.Integer(), nullable=False),
    sa.Column('hours_with_missing_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_name', 'ean_number', 'month', name='uq_monthly_totals')
    )
    with op.batch_alter_table('monthly_totals', schema=None) as batch_op:
        batch_op.create_index('ix_monthly_totals_month', ['month'], unique=False)
        batch_op.create_index('ix_monthly_totals_site_ean', ['site_name', 'ean_number'], unique=False)

    op.create_table('spot_prices_quarter_hourly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp_local', sa.DateTime(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=False),
    sa.Column('price_eur_mwh_raw_micro', sa.Integer(), nullable=False),
    sa.Column('price_eur_kwh_transformed_micro', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp_utc', 'source_key', name='uq_spot_prices_ts_source')
    )
    with op.batch_alter_table('spot_prices_quarter_hourly', schema=None) as batch_op:
        batch_op.create_index('ix_spot_prices_timestamp_local', ['timestamp_local'], unique=False)

    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.create_index('ix_data_quality_issues_batch', ['import_batch_id'], unique=False)

    op.create_table('energy_readings_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('ean_number', sa.String(length=64), nullable=True),
    sa.Column('meter_number', sa.String(length=64), nullable=True),
    sa.Column('raw_data_period', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('variable_name', sa.String(length=255), nullable=True),
    sa.Column('granularity', sa.String(length=32), nullable=True),
    sa.Column('aggregation', sa.String(length=32), nullable=True),
    sa.Column('raw_data_period_frequency', sa.Integer(), nullable=True),
    sa.Column('data_time_raw', sa.Text(), nullable=True),
    sa.Column('data_time_local', sa.DateTime(), nullable=True),
    sa.Column('data_time_utc', sa.DateTime(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('value_kwh_milli', sa.Integer(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash', name='uq_energy_readings_dedup_hash')
    )
    with op.batch_alter_table('energy_readings_raw', schema=None) as batch_op:
        batch_op.create_index('ix_energy_readings_import_batch', ['import_batch_id'], unique=False)
        batch_op.create_index('ix_energy_readings_site_ean_time', ['site_name', 'ean_number', 'data_time_utc'], unique=False)

    # Vue SQL reproduisant la feuille « Récap ».
    from app.views import RECAP_VIEW_SQL

    op.execute(RECAP_VIEW_SQL)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS recap_hourly")

    with op.batch_alter_table('energy_readings_raw', schema=None) as batch_op:
        batch_op.drop_index('ix_energy_readings_site_ean_time')
        batch_op.drop_index('ix_energy_readings_import_batch')

    op.drop_table('energy_readings_raw')
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.drop_index('ix_data_quality_issues_batch')

    op.drop_table('data_quality_issues')
    with op.batch_alter_table('spot_prices_quarter_hourly', schema=None) as batch_op:
        batch_op.drop_index('ix_spot_prices_timestamp_local')

    op.drop_table('spot_prices_quarter_hourly')
    with op.batch_alter_table('monthly_totals', schema=None) as batch_op:
        batch_op.drop_index('ix_monthly_totals_site_ean')
        batch_op.drop_index('ix_monthly_totals_month')

    op.drop_table('monthly_totals')
    op.drop_table('import_batches')
    with op.batch_alter_table('energy_hourly', schema=None) as batch_op:
        batch_op.drop_index('ix_energy_hourly_timestamp')
        batch_op.drop_index('ix_energy_hourly_site_ean')

    op.drop_table('energy_hourly')
    op.drop_table('app_metadata')
    # ### end Alembic commands ###
